import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import { Rubik } from "next/font/google";
import { dirFor } from "@/lib/i18n";
import { getAudience } from "@/lib/audience";
import { THEME_COOKIE, THEME_BOOTSTRAP, isTheme } from "@/lib/theme";
import "./globals.css";

// One grotesk for headline and body, Hebrew and Latin, so nothing falls back mid-line.
const rubik = Rubik({ subsets: ["hebrew", "latin"], variable: "--font-rubik" });

export const metadata: Metadata = {
  title: "FitMeter — Your Week, Scored",
  description: "Log your workouts. Get a weekly Fit Score. Beat your friends.",
  // Icons come from the app/icon.svg, app/apple-icon.png and app/manifest.ts conventions
  // (all generated by scripts/generate-icons.mjs).
  appleWebApp: { title: "FitMeter", statusBarStyle: "default" },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FFFFFF" },
    { media: "(prefers-color-scheme: dark)", color: "#0A0A0A" },
  ],
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const jar = await cookies();
  // The same resolution the pages use (cookie, else the signed-in user's stored
  // preference), so lang/dir can't disagree with the strings rendered inside them.
  const { locale } = await getAudience();
  const cookieTheme = jar.get(THEME_COOKIE)?.value;

  return (
    <html
      lang={locale}
      dir={dirFor(locale)}
      // The bootstrap script may add `dark` before React hydrates.
      suppressHydrationWarning
      className={`${rubik.variable} ${isTheme(cookieTheme) && cookieTheme === "dark" ? "dark" : ""}`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP }} />
      </head>
      <body className="bg-canvas font-body text-ink antialiased">{children}</body>
    </html>
  );
}
