import type { MetadataRoute } from "next";

/**
 * Makes "Add to home screen" produce a named, iconed app instead of a grey tile.
 * The PNGs are generated by scripts/generate-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "FitMeter",
    short_name: "FitMeter",
    description: "Log your workouts. Get a weekly Fit Score. Beat your friends.",
    start_url: "/dashboard",
    display: "standalone",
    background_color: "#FFFFFF",
    theme_color: "#0A0A0A",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
    ],
  };
}
